import { describe, expect, it } from "vitest";

import { CURRENT_SCHEMA_VERSION, parseAndMigrateBackup } from "@/lib/backup";
import { DEFAULT_UNIT_ECONOMICS } from "@/lib/defaults";

describe("guide progress migration", () => {
  it("migrates schema v3 payload to v4 with guide defaults", () => {
    const payload = {
      schemaVersion: 3,
      settings: {
        schemaVersion: 3,
        baseCurrency: { code: "MXN", symbol: "$" },
        currencyDisplayMode: "base",
        fxRateToUsd: 20,
        businessModel: "other",
      },
      progress: {
        completedChapterSlugs: [],
        bookmarks: [],
        dismissedTipIds: ["cashflow-starting-balance"],
        toolSampleState: { cashflow: "active" },
        activeLearningLayer: "base",
      },
      cashflow: [],
      costs: [],
      budget: [],
      breakeven: null,
      unitEconomics: DEFAULT_UNIT_ECONOMICS,
      financingOptions: {
        optionType: "debt",
        principal: 1,
        annualRatePct: 1,
        termMonths: 1,
        fees: 0,
        otherCosts: 0,
        equityOfferedPct: 0,
        controlScore: 0,
        riskScore: 0,
        flexibilityScore: 0,
      },
      debtManager: {
        totalDebt: 0,
        totalAssets: 1,
        ebit: 0,
        interestExpense: 1,
        loanAmount: 1,
        fees: 0,
        otherCosts: 0,
        primaryBalance: 0,
        primaryRatePct: 0,
        secondaryBalance: 0,
        secondaryRatePct: 0,
        oldTotalCost: 0,
        newTotalCost: 0,
      },
      profitabilityAnalyzer: {
        sales: 1,
        cogs: 0,
        opex: 0,
        netIncome: 0,
        investment: 1,
        segmentRevenue: 1,
        segmentCosts: 0,
      },
      financialStrategyPlanner: {
        revenue0: 1,
        growthRatePct: 1,
        targetNetMarginPct: 1,
        reinvestPct: 1,
        dividendPct: 1,
        debtPct: 1,
        equityPct: 1,
        maxDebtPct: 2,
        horizonYears: 1,
      },
      contingencyPlanner: {
        riskName: "x",
        probabilityPct: 1,
        impactPct: 1,
        monthlyFixedOutflow: 1,
        reserveMonths: 1,
        reserveBalance: 1,
        trigger: "x",
        owner: "x",
        responseTimeDays: 1,
      },
      financialEducationKit: {
        role: "x",
        testScore1: 1,
        testScore2: 1,
        testScore3: 1,
        completedModules: 1,
        totalModules: 1,
        trainingCost: 1,
        profitImprovement: 1,
      },
      investmentEvaluator: {
        investmentId: "x",
        initialCost: 1,
        annualBenefit: 1,
        discountRatePct: 1,
        years: 1,
        scenario: "base",
      },
      businessModelAnalyzer: {
        model: "other",
        sales: 1,
        cogs: 0,
        marketingSales: 0,
        newCustomers: 1,
        ltv: 1,
        churnPct: 1,
        capacityUsedPct: 1,
        benchmark: 1,
        target: 1,
      },
      internationalFinanceManager: {
        currencyCode: "USD",
        foreignAmount: 1,
        plannedRate: 1,
        actualRate: 1,
        hedgedResult: 1,
        unhedgedResult: 1,
        basePrice: 1,
        fxRiskBufferPct: 1,
      },
      fintechEvaluator: {
        tool: "x",
        needsCoverageScore: 1,
        securityScore: 1,
        integrationScore: 1,
        easeScore: 1,
        annualCost: 1,
        annualBenefit: 1,
        dataRiskScore: 1,
        operationalRiskScore: 1,
        vendorRiskScore: 1,
      },
      valuationCalculator: {
        annualSales: 1,
        salesMultiple: 1,
        annualEbitda: 1,
        ebitdaMultiple: 1,
        annualNetIncome: 1,
        netIncomeMultiple: 1,
        totalAssets: 1,
        totalLiabilities: 1,
        discountRatePct: 1,
        freeCashFlow: 1,
        terminalValue: 1,
        years: 1,
      },
      resilienceEvaluator: {
        availableCash: 1,
        monthlyBurn: 1,
        monthlyOperatingExpense: 1,
        targetMonths: 1,
        liquidityScore: 1,
        debtScore: 1,
        diversificationScore: 1,
        contingencyReadinessScore: 1,
        salesDropPct: 1,
      },
    };

    const parsed = parseAndMigrateBackup(payload);

    expect(parsed.schemaVersion).toBe(CURRENT_SCHEMA_VERSION);
    expect(parsed.progress.dismissedGuideBlocks).toEqual([]);
    expect(parsed.progress.toolStepProgress).toEqual({});
    expect(parsed.progress.toolSampleState.cashflow).toBe("active");
  });
});
